### ISSUE TITLE
Error(s) in loading state_dict for Resampler: size mismatch for proj_in.weight

### ISSUE THREAD

**Issue by RCHZ** [yvann-ba/ComfyUI_Yvann-Nodes#7]
# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapterBatch
- **Exception Type:** RuntimeError
- **Exception Message:** Error(s) in loading state_dict for Resampler:
	size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).
## Stack Trace
```
  File "C:\Users\roach\pinokio\api\comfyui.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\Users\roach\pinokio\api\comfyui.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\Users\roach\pinokio\api\comfyui.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\roach\pinokio\api\comfyui.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 822, in apply_ipadapter
    work_model, face_image = ipadapter_execute(work_model, ipadapter_model, clip_vision, **ipa_args)

  File "C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 441, in ipadapter_execute
    ipa = IPAdapter(

  File "C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 71, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])

  File "C:\Users\roach\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

```
## System Information
- **ComfyUI Version:** v0.2.4-10-g5cbb01b
- **Arguments:** main.py --disable-xformers
- **OS:** nt
- **Python Version:** 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12878086144
  - **VRAM Free:** 7527935996
  - **Torch VRAM Total:** 3992977408
  - **Torch VRAM Free:** 18034684

## Logs
```
2024-10-26 09:57:07,166 - root - INFO - Total VRAM 12282 MB, total RAM 65384 MB
2024-10-26 09:57:07,167 - root - INFO - pytorch version: 2.3.1+cu121
2024-10-26 09:57:07,167 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-26 09:57:07,167 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
2024-10-26 09:57:07,913 - root - INFO - Using pytorch cross attention
2024-10-26 09:57:08,815 - root - INFO - [Prompt Server] web root: C:\Users\roach\pinokio\api\comfyui.git\app\web
2024-10-26 09:57:09,607 - root - INFO - Total VRAM 12282 MB, total RAM 65384 MB
2024-10-26 09:57:09,607 - root - INFO - pytorch version: 2.3.1+cu121
2024-10-26 09:57:09,607 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-26 09:57:09,607 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
2024-10-26 09:57:09,976 - OpenGL.acceleratesupport - INFO - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
2024-10-26 09:57:11,036 - root - INFO - 
Import times for custom nodes:
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\websocket_image_save.py
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\cg-use-everywhere
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Image-Saver
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\comfy-image-saver
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\rgthree-comfy
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\efficiency-nodes-comfyui
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-KJNodes
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_Yvann-Nodes
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-26 09:57:11,036 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-10-26 09:57:11,037 - root - INFO -    0.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\comfyui_controlnet_aux
2024-10-26 09:57:11,037 - root - INFO -    0.1 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-26 09:57:11,037 - root - INFO -    0.2 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Manager
2024-10-26 09:57:11,037 - root - INFO -    0.4 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack
2024-10-26 09:57:11,037 - root - INFO -    1.0 seconds: C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_Fill-Nodes
2024-10-26 09:57:11,037 - root - INFO - 
2024-10-26 09:57:11,047 - root - INFO - Starting server

2024-10-26 09:57:11,048 - root - INFO - To see the GUI go to: 
2024-10-26 09:58:20,201 - root - INFO - got prompt
2024-10-26 09:58:23,750 - py.warnings - WARNING - C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_Yvann-Nodes\nodes\audio\Audio_Reactive_Yvann.py:186: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.figure(figsize=(figsize, figsize * 0.6), facecolor='white')

2024-10-26 09:58:24,286 - dinov2 - INFO - using MLP layer as FFN
2024-10-26 09:58:41,318 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-26 09:58:41,318 - root - INFO - model_type EPS
2024-10-26 09:58:41,601 - root - INFO - Using pytorch attention in VAE
2024-10-26 09:58:41,602 - root - INFO - Using pytorch attention in VAE
2024-10-26 09:58:41,804 - py.warnings - WARNING - C:\Users\roach\pinokio\api\comfyui.git\app\env\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

2024-10-26 09:58:42,199 - root - INFO - Requested to load SD1ClipModel
2024-10-26 09:58:42,199 - root - INFO - Loading 1 new model
2024-10-26 09:58:42,265 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-10-26 09:58:42,295 - py.warnings - WARNING - C:\Users\roach\pinokio\api\comfyui.git\app\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)

2024-10-26 09:58:42,351 - root - INFO - Using pytorch attention in VAE
2024-10-26 09:58:42,352 - root - INFO - Using pytorch attention in VAE
2024-10-26 09:58:42,471 - root - WARNING - Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
2024-10-26 09:58:43,062 - py.warnings - WARNING - C:\Users\roach\pinokio\api\comfyui.git\app\env\lib\site-packages\torchvision\transforms\v2\_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(

2024-10-26 09:58:43,189 - py.warnings - WARNING - C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_Yvann-Nodes\nodes\audio\IPAdapter_Audio_Reactive_Yvann.py:150: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.figure(figsize=(figsize, figsize * 0.6), facecolor='white')

2024-10-26 09:58:43,594 - root - WARNING - Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
2024-10-26 09:58:45,167 - root - INFO - Requested to load CLIPVisionModelProjection
2024-10-26 09:58:45,167 - root - INFO - Loading 1 new model
2024-10-26 09:58:45,759 - root - INFO - loaded completely 0.0 3522.953369140625 True
2024-10-26 09:58:48,888 - root - ERROR - !!! Exception during processing !!! Error(s) in loading state_dict for Resampler:
	size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).
2024-10-26 09:58:48,889 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\roach\pinokio\api\comfyui.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Users\roach\pinokio\api\comfyui.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Users\roach\pinokio\api\comfyui.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\roach\pinokio\api\comfyui.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 822, in apply_ipadapter
    work_model, face_image = ipadapter_execute(work_model, ipadapter_model, clip_vision, **ipa_args)
  File "C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 441, in ipadapter_execute
    ipa = IPAdapter(
  File "C:\Users\roach\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 71, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
  File "C:\Users\roach\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Resampler:
	size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).

2024-10-26 09:58:48,892 - root - INFO - Prompt executed in 28.43 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by RCHZ** [comment]
I realized this was an ipadapter issue and was able to get everything to work by switching from PLUS (high strength) to VIT-G (medium strength) in the ipadapter unified loader.
